version: '3.8'

services:
  mongodb:
    image: mongo:latest
    container_name: telebot_mongodb
    ports:
      - "27017:27017"
    environment:
      MONGO_INITDB_ROOT_USERNAME: admin          # Set the root username
      MONGO_INITDB_ROOT_PASSWORD: Abcd_1234      # Set the root password
    volumes:
      - mongodb_data:/data/db

volumes:
  mongodb_data:
    driver: local